# Generated by Django 3.1.6 on 2021-02-20 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_thought'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thought',
            name='thought_text',
            field=models.TextField(),
        ),
    ]
